baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "WebStack网址导航 Hugo主题"
# theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "iplaycode"
  description = "Webstack Hugo"
[params.search]
  enable = true
# [params.darkmode]
#   enable = true
[params.nav]
  enable = true
[params.https] #强制js跳转 https
  enable = false 